### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by lavaJockey** [fgsfdsfgs/gzdoom#1]
![notepad_2bRvj7SXT3](https://user-images.githubusercontent.com/31358302/57584400-d0ec8500-74a8-11e9-948e-aefa4eb559e0.png)

**Comment by fgsfdsfgs** [comment]
This error can occur if a GL application was started before and didn't deinitialize OpenGL related stuff properly. Delete error.log, restart hbmenu and try again.
I also need additional information: firmware version, how did you get this error, GZDoom directory layout on SD card, etc.

**Comment by lavaJockey** [comment]
It booted this time around!
