### ISSUE TITLE
Brutal Doom Doesn't Load

### ISSUE THREAD

**Issue by GoobyCorp** [fgsfdsfgs/gzdoom#182]
For some reason I can find videos online of people playing brutal doom but I can't manage to get it to work myself, it always comes up with an error saying unable to realloc or malloc. My switch is on firmware version 8.1.0 and Atmosphere 0.9.3 with gzdoom version 4 and Brutal Doom v21 Gold.

**Comment by fgsfdsfgs** [comment]
You have to launch hbmenu from game override, not from the Album, because applet/album mode doesn't provide enough memory for BD. Hold R (or L?) while starting a game to do that.

**Comment by GoobyCorp** [comment]
Thanks for the answer, that solved my problem. I'm surprised I didn't know that before.
