### ISSUE TITLE
Controls won't work

### ISSUE THREAD

**Issue by elracing** [fgsfdsfgs/gzdoom#208]
Update 9.0.0 broke HID, controls wont work.

**Comment by parkerlreed** [comment]
If you're using Atmosphere it should have a shim to let the old HID routine work. 

Just tested here and it's working. You are correct though as this will need a new release as the shim it Atmosphere isn't going to be permanent.

**Comment by elracing** [comment]
How exactly you put it to work anyways? just booting into a title and then into homebrew by holding R isnt doing it for me

**Comment by parkerlreed** [comment]
That's exactly how you launch it. 

I have a newer release you can try out. Built against 8093

https://amdpowered.com/eduke32_nx_8093_1.zip

**Comment by elracing** [comment]
Lmao, still nice to know about that which you just uploaded. But yea, in our isnt working for me at all, I do get to the title selection screen and even load the game directly if I select gzdoom itself, but no input is detected at all by pressing any button on joycons. Wonder what's different between your set up and mines. Do you have to enable the hid mitm manually or something? Cant think of much else

**Comment by parkerlreed** [comment]
Yeah same Atmos version. I am on Kosmos but that shouldn't make a difference. The HID workaround is just there. Do you maybe have the older mitm module enabled? It seems the current woraround is going to be removed since it interferes with that. 

>This mitm will be removed in a future Atmosphere revision once homebrew has been updated, to allow users to use a custom hid mitm again if they desire.

**Comment by elracing** [comment]
I havent touched any settings, left everything on 0.9.4 as it came, so I dont think I have the older mitm module enabled, how do I enable it anyways?

**Comment by parkerlreed** [comment]
The older one? I just meant that its a sysmodule you could have used to use other controllers via youur phone. 

The new one there's nothing to enable. It's just there.

**Comment by elracing** [comment]
Oh thaaaat, I know what you re talking about lol. Pretty much just digging around because there must be a reason for it to not work on mines, so bizarre.

**Comment by elracing** [comment]
Figured out the issue based on input from others and testing it myself. It's tinfoil, it screwed up with atmosphere, as soon as I replaced tinfoil's forked atmosphere files with the vanilla atmosphere files everything got fixed. Still leaving this ticket up since it'll be relevant in the coming updates.

**Comment by parkerlreed** [comment]
Yeah I was just about to post that  
![Screenshot_20190924-094344](https://user-images.githubusercontent.com/841440/65516909-da9ee400-deaf-11e9-9312-b36a0b210e5f.png)

**Comment by fgsfdsfgs** [comment]
In any case, this has been rebuilt with 9.0 support now, so whatever.
