### ISSUE TITLE
Launcher ignores all input

### ISSUE THREAD

**Issue by sava1978** [fgsfdsfgs/gzdoom#258]
If you launch the game by itself, the problem persists. I am using a doom 2 wad. I have been trying other wads but the result is always the same.

**Comment by fgsfdsfgs** [comment]
Take a look at [this issue](https://github.com/fgsfdsfgs/gzdoom/issues/208). Make sure you have the [latest release](https://github.com/fgsfdsfgs/gzdoom/releases/tag/nx4.3pre-5) too.

**Comment by sava1978** [comment]
Thanks! I needed to launch it through the R button!
