### ISSUE TITLE
Doom2 Pwads won't load or appear ingame

### ISSUE THREAD

**Issue by PostModernHuman** [fgsfdsfgs/gzdoom#261]
I am not sure if it has something to do with the wads themselves or the pk3 files but when booting Doom2 with any addons the games loads as normal. But when I select mods and boot it with The Ultimate Doom it boots perfectly fine. I have checked which mods work with Doom1 and Doom2 and most do work with Doom2. But the Gzdoom launcher has an issue adding it to Doom2. Also sometimes but rarely will the Doom hud revert to the classic Hud and other settings changed. The only thing I mess with in the settings are controls but it has happened at least 3 times, and I do close the launcher correctly.

**Comment by fgsfdsfgs** [comment]
Did you select Doom 2 first and then select the pwads?

**Comment by PostModernHuman** [comment]
Uh, no? I actually didn't know I had to do that. I assumed I had to first set which pwads I wanted then selected the WAD i wanted to boot. I also found that the pwads work with TNT.wad but not the ThePlutoniumExperiment.wad. Either way, how do I select Doom2 then the pwads because I can't find an option like that on the menu. Thanks!

**Comment by fgsfdsfgs** [comment]
Nah, the way it works is on the profiles screen you pick Doom 2, then you pick your pwads. They're tied to the game. I don't recall the exact details of how I implemented it though.

**Comment by PostModernHuman** [comment]
Oh okay, I understand now. Let me give that a go and see if that fixes my problem. Thanks again!

**Comment by PostModernHuman** [comment]
Omg it worked, that also explains why I would see pwads already selected. Thanks man! Also thanks on the amazing work of getting Gzdoom working on switch, I appreciate your help and work! Rip and Tear, my man!
