### ISSUE TITLE
[Feature] Ability to create profiles of mod files for quick launching

### ISSUE THREAD

**Issue by seldan700** [fgsfdsfgs/gzdoom#263]
### GZDoom version

Switch Release 8, GZdoom launcher

### Which game are you running with GZDoom?

None

### What Operating System are you using?

Other

### If Other OS, please describe

Switch

### Is your feature request related to a problem? Please describe.

I want to play Brutal Doom 64, which uses 4 different pk3 files. 

### Describe the solution you'd like

Instead of having to go through the menus and select all of them every time I want to play, I was wondering if it would be possible to implement a feature to create a profile with all the pk3s so I can just select Brutal Doom 64 from the profiles list and get right into it.

**Comment by parkerlreed** [comment]
I believe this already exists? 

The docs says

> The launcher has predefined default profiles for most supported IWADs. You can also add your own profiles by pressing Y on the main tab. Any changes will be saved to gzdoom/launcher.ini.

**Comment by seldan700** [comment]
> I believe this already exists?
> 
> The docs says
> 
> > The launcher has predefined default profiles for most supported IWADs. You can also add your own profiles by pressing Y on the main tab. Any changes will be saved to gzdoom/launcher.ini.

This only applies to IWADS, I am requesting this feature for PWADS.

**Comment by fgsfdsfgs** [comment]
I think you can just make multiple profiles with the same IWAD but different sets of PWADs?

**Comment by seldan700** [comment]
> I think you can just make multiple profiles with the same IWAD but different sets of PWADs?

Would I need to do this in the ini file or is this possible within the gui?

My Doom profile looks like this:
[Doom]
IWAD = doom.wad
JoinAddr = 192.168.0.22:5029
MaxPlayers = 1
Monsters = 0

Could I create a new profile with the desired mods by adding something like this?
[xxxxxxx]
IWAD = doom.wad
**PWAD = xxx.pk3, xxxx.pk3**
JoinAddr = 192.168.0.22:5029
MaxPlayers = 1
Monsters = 0

**Comment by fgsfdsfgs** [comment]
I think it's possible to do from the GUI. I haven't touched the thing in a while, so I don't remember.
Yeah, you should be able to add one to the .ini like so:
 ```
[Cool mods]
IWAD = doom2.wad
File = mod1.pk3
File = mod2.pk3
JoinAddr = 192.168.0.22:5029
MaxPlayers = 1
Monsters = 0
```

**Comment by seldan700** [comment]
> I think it's possible to do from the GUI. I haven't touched the thing in a while, so I don't remember. Yeah, you should be able to add one to the .ini like so:
> 
> ```
> [Cool mods]
> IWAD = doom2.wad
> File = mod1.pk3
> File = mod2.pk3
> JoinAddr = 192.168.0.22:5029
> MaxPlayers = 1
> Monsters = 0
> ```

Good to know, thank you. However, I cannot seem to do it from the gui, as the new profile button only allows me to add new IWADS.
